version: "3.9"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5454:5432"
  migrations:
    build:
      context: backend
    command: python manage.py migrate
    depends_on:
      - db
  backend:
    build:
      dockerfile: Dockerfile
      context: backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/corpapp:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - migrations
  frontend:
      build:
        dockerfile: Dockerfile
        context: frontend
      ports:
        - "3000:3000"
      volumes:
        - ./frontend/src:/app/src
